PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT ?subCatalogURL
WHERE {
    ?catlog rdf:type        schema:CreativeWork ;
            schema:hasPart  ?subCatalogURL      .
} ORDER BY ?subCatalogURL