services:
  fuseki:
    image: stain/jena-fuseki:latest
    volumes:
      - "./fuseki:/fuseki"
      - "./fuseki-server.jar:/jena-fuseki/fuseki-server.jar"
    ports:
      - 3030:3030
    environment: 
      - ADMIN_PASSWORD=test123
      - FUSEKI_DATASET_1=FAIR-EASE
      - JVM_ARGS=-Xmx800M
